import { Router, type IRouter } from "express";

const router: IRouter = Router();

type ProjectType = "react-vite" | "express-api" | "expo-mobile" | "python-fastapi" | "fullstack-monorepo";
type DeployTarget = "github-pages" | "vercel" | "railway" | "fly-io" | "aws-ec2" | "none";

function generateActionsYaml(
  projectType: ProjectType,
  deployTarget: DeployTarget,
  features: string[],
  repoName: string
): { filename: string; yaml: string; secretsNeeded: string[]; setupInstructions: string } {
  const hasDocker = features.includes("docker");
  const hasLint = features.includes("lint");
  const hasTest = features.includes("test");
  const hasSecScan = features.includes("security-scan");

  const secretsNeeded: string[] = [];
  let deployStep = "";

  if (deployTarget === "vercel") {
    secretsNeeded.push("VERCEL_TOKEN", "VERCEL_ORG_ID", "VERCEL_PROJECT_ID");
    deployStep = `
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: \${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: \${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: \${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'`;
  } else if (deployTarget === "railway") {
    secretsNeeded.push("RAILWAY_TOKEN");
    deployStep = `
      - name: Deploy to Railway
        uses: bervProject/railway-deploy@main
        with:
          railway_token: \${{ secrets.RAILWAY_TOKEN }}`;
  } else if (deployTarget === "fly-io") {
    secretsNeeded.push("FLY_API_TOKEN");
    deployStep = `
      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: \${{ secrets.FLY_API_TOKEN }}`;
  } else if (deployTarget === "github-pages") {
    deployStep = `
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: \${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist`;
  }

  let buildSteps = "";

  if (projectType === "react-vite" || projectType === "fullstack-monorepo") {
    buildSteps = `
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Type check
        run: pnpm run typecheck
      ${hasLint ? "- name: Lint\n        run: pnpm run lint" : ""}
      ${hasTest ? "- name: Test\n        run: pnpm run test" : ""}
      - name: Build
        run: pnpm run build`;
  } else if (projectType === "express-api") {
    buildSteps = `
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Type check
        run: pnpm run typecheck
      ${hasTest ? "- name: Test\n        run: pnpm run test" : ""}
      - name: Build
        run: pnpm run build`;
  } else if (projectType === "python-fastapi") {
    buildSteps = `
      - name: Install dependencies
        run: pip install -r requirements.txt
      ${hasLint ? "- name: Lint\n        run: ruff check ." : ""}
      ${hasTest ? "- name: Test\n        run: pytest" : ""}`;
  } else if (projectType === "expo-mobile") {
    secretsNeeded.push("EXPO_TOKEN");
    buildSteps = `
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: \${{ secrets.EXPO_TOKEN }}
      - name: Build Expo app
        run: eas build --platform all --non-interactive`;
  }

  const securityStep = hasSecScan
    ? `
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run security audit
        run: pnpm audit --audit-level high
      - name: SAST Scan
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript`
    : "";

  const dockerStep = hasDocker
    ? `
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/\${{ github.repository }}:latest`
    : "";

  const yaml = `# Generated by The Brain — github.com/artyloks/The-Data-Base
# Project: ${repoName || projectType}
# Deploy target: ${deployTarget}

name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

concurrency:
  group: \${{ github.workflow }}-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
${buildSteps}
${dockerStep}
${deployStep ? `
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
${deployStep}` : ""}
${securityStep}
`;

  const setupInstructions = `
## Setup Instructions

1. Copy this file to \`.github/workflows/ci.yml\` in your repo
2. ${secretsNeeded.length > 0 ? `Add these secrets in GitHub → Settings → Secrets → Actions:\n   ${secretsNeeded.map((s) => `• ${s}`).join("\n   ")}` : "No secrets needed — uses GITHUB_TOKEN automatically"}
3. Push to main to trigger your first run

## Local dev (extracted from CI)
\`\`\`bash
pnpm install
pnpm run typecheck
pnpm run build
\`\`\`
`.trim();

  return {
    filename: ".github/workflows/ci.yml",
    yaml,
    secretsNeeded,
    setupInstructions,
  };
}

router.post("/generate-actions", (req, res) => {
  const { projectType, deployTarget, features = [], repoName = "" } = req.body as {
    projectType: ProjectType;
    deployTarget: DeployTarget;
    features?: string[];
    repoName?: string;
  };

  if (!projectType || !deployTarget) {
    res.status(400).json({ error: "projectType and deployTarget are required" });
    return;
  }

  const result = generateActionsYaml(projectType, deployTarget, features, repoName);
  res.json(result);
});

export default router;
